#!/usr/bin/env perl
use v5.42;
use warnings;
use experimental qw(signatures);

use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../local/lib/perl5";

use Mojolicious::Commands;
Mojolicious::Commands->start_app('CoreSmoke::App');
